// Users Table
export const USERS_TABLE = 'USERS_TABLE';

// User Form
export const USER_FORM_TRIGGER = 'USER_FORM_TRIGGER';
export const USER_FORM_FORM_CONTROL_GENDER = 'USER_FORM_FORM_CONTROL_GENDER';
export const USER_FORM_FORM_CONTROL_GENDER_OPTION_FEMALE =
	'USER_FORM_FORM_CONTROL_GENDER_OPTION_FEMALE';
export const USER_FORM_FORM_CONTROL_GENDER_OPTION_MALE =
	'USER_FORM_FORM_CONTROL_GENDER_OPTION_MALE';
export const USER_FORM_FORM_CONTROL_FIRST_NAME = 'USER_FORM_FORM_CONTROL_FIRST_NAME';
export const USER_FORM_FORM_CONTROL_LAST_NAME = 'USER_FORM_FORM_CONTROL_LAST_NAME';
export const USER_FORM_FORM_CONTROL_AGE = 'USER_FORM_FORM_CONTROL_AGE';
export const USER_FORM_FORM_CONTROL_AGE_ERROR = 'USER_FORM_FORM_CONTROL_AGE_ERROR';
export const USER_FORM_ACTION_SUBMIT = 'USER_FORM_ACTION_SUBMIT';

// Common
export const GLOBAL_NOTIFICATION = 'GLOBAL_NOTIFICATION';
